// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6VMfJ0g4w8FQ0ykEyl3ZYVopmzFsJySU',
    appId: '1:119321029884:web:edce34b10830e4aaa93b79',
    messagingSenderId: '119321029884',
    projectId: 'test-71c91',
    authDomain: 'test-71c91.firebaseapp.com',
    storageBucket: 'test-71c91.appspot.com',
    measurementId: 'G-Q1KR65DME6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tCLncjbqo9yM0SR7KVCch1XQW2oj3Ec',
    appId: '1:119321029884:android:7bbf46bcfd0e3400a93b79',
    messagingSenderId: '119321029884',
    projectId: 'test-71c91',
    storageBucket: 'test-71c91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhBR1ZBFN6aCXf6RVQXA5VpE6x7AlfoU',
    appId: '1:119321029884:ios:a1b24c1ffea402e9a93b79',
    messagingSenderId: '119321029884',
    projectId: 'test-71c91',
    storageBucket: 'test-71c91.appspot.com',
    androidClientId: '119321029884-s9v8fq6q6m807r2ii3cg2vaq280o6j7d.apps.googleusercontent.com',
    iosClientId: '119321029884-jrbkhtflo8fqnkecl1gu34n4fp70989o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGuide',
  );
}
